[project]
name = "boot-aiagent"
version = "0.1.0"
description = "boot.dev ai agent project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai==1.12.1",
    "python-dotenv==1.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.2",
]
